version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # use variable in .env file
    # env_file: 
    #     - ./.env 
    environment:
      - DATABASE_HOSTNAME=localhost 
      - DATABASE_PORT=5432  
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres 
      - SECRET_KEY=975439b3dffec373c02bd1bb326e485ebee2441c9703f9311bf80a792a234be3 
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    # use your own varaiable
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: